XML File:14065000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14065000.xml", line 166853
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: Year line 65535 and Yuar, line 166853, column 43

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14095000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14095000.xml", line 33036
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: AbstractText line 33036 and ArstractText, line 33036, column 722

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14100000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14100000.xml", line 7841
lxml.etree.XMLSyntaxError: Specification mandates value for attribute PubMode, line 7841, column 25

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14105000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14105000.xml", line 53600
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DescriptorName line 53600 and DescriptorNamu, line 53600, column 116

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:14115000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14115000.xml", line 17470
lxml.etree.XMLSyntaxError: error parsing attribute name, line 17470, column 26

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14120000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14120000.xml", line 46266
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: MeshHeading line 46263 and MeshHeadinw, line 46266, column 37

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14125000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14125000.xml", line 287901
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: RegistryNumber line 65535 and RegistryNumbur, line 287901, column 72

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14130000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14130000.xml", line 343248
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DescryptorName line 65535 and DescriptorName, line 343248, column 98

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14145000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14145000.xml", line 355597
lxml.etree.XMLSyntaxError: error parsing attribute name, line 355597, column 30

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14150000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14150000.xml", line 309974
lxml.etree.XMLSyntaxError: error parsing attribute name, line 309974, column 18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:14155000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14155000.xml", line 141978
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: Yeqr line 65535 and Year, line 141978, column 36

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

XML File:14175000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14175000.xml", line 88722
lxml.etree.XMLSyntaxError: error parsing attribute name, line 88722, column 28

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14200000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14200000.xml", line 191435
lxml.etree.XMLSyntaxError: error parsing attribute name, line 191435, column 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:14280000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14280000.xml", line 704400
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: PMID line 65535 and PMYD, line 704400, column 51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14345000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14345000.xml", line 119347
lxml.etree.XMLSyntaxError: error parsing attribute name, line 119347, column 28

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14375000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14375000.xml", line 168870
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: Yssue line 65535 and Issue, line 168870, column 37

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14390000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14390000.xml", line 192934
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: Xistory line 65535 and History, line 192934, column 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:14395000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14395000.xml", line 30175
lxml.etree.XMLSyntaxError: error parsing attribute name, line 30175, column 30

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14410000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14410000.xml", line 122600
lxml.etree.XMLSyntaxError: error parsing attribute name, line 122600, column 22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14450000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14450000.xml", line 269344
lxml.etree.XMLSyntaxError: Specification mandates value for attribute ValidY, line 269344, column 31

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14505000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14505000.xml", line 93223
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: PublicationTypu line 65535 and PublicationType, line 93223, column 111

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

XML File:14530000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14530000.xml", line 236288
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DessriptorName line 65535 and DescriptorName, line 236288, column 92

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14545000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14545000.xml", line 534308
lxml.etree.XMLSyntaxError: AttValue: " or ' expected, line 534308, column 36

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:14550000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14550000.xml", line 68494
lxml.etree.XMLSyntaxError: Specification mandates value for attribute Iss, line 68494, column 26

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14610000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14610000.xml", line 295784
lxml.etree.XMLSyntaxError: Specification mandates value for attribute MajorT, line 295784, column 52

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14620000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14620000.xml", line 393322
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: MeshHeqding line 65535 and MeshHeading, line 393322, column 33

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:14660000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14660000.xml", line 431074
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DescryptorName line 65535 and DescriptorName, line 431074, column 90

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:14670000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/14670000.xml", line 662442
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: RufSource line 65535 and RefSource, line 662442, column 71

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 63, in getTerms
    mesh.append(m.find('NameOfSubstance').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:18475000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/18475000.xml", line 29035
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: PMIT line 29035 and PMID, line 29035, column 53

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 84, in parse
    pmid= elem.find('MedlineCitation').find('PMID').text # First PMID is the right one
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 84, in parse
    pmid= elem.find('MedlineCitation').find('PMID').text # First PMID is the right one
AttributeError: 'NoneType' object has no attribute 'find'

XML File:18810000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/18810000.xml", line 175103
lxml.etree.XMLSyntaxError: AttValue: " or ' expected, line 175103, column 36

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:19125000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/19125000.xml", line 108418
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DessriptorName line 65535 and DescriptorName, line 108418, column 94

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21350000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21350000.xml", line 236887
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DescriptorNamu line 65535 and DescriptorName, line 236887, column 114

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21355000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21355000.xml", line 96511
lxml.etree.XMLSyntaxError: expected '>', line 96511, column 46

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21365000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21365000.xml", line 53120
lxml.etree.XMLSyntaxError: error parsing attribute name, line 53120, column 21

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21370000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21370000.xml", line 135792
lxml.etree.XMLSyntaxError: Specification mandates value for attribute Maj, line 135792, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 84, in parse
    pmid= elem.find('MedlineCitation').find('PMID').text # First PMID is the right one
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 84, in parse
    pmid= elem.find('MedlineCitation').find('PMID').text # First PMID is the right one
AttributeError: 'NoneType' object has no attribute 'find'

XML File:21385000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21385000.xml", line 86725
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: TescriptorName line 65535 and DescriptorName, line 86725, column 86

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21410000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21410000.xml", line 505959
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: Keyword line 65535 and Keywort, line 505959, column 77

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

XML File:21480000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21480000.xml", line 325092
lxml.etree.XMLSyntaxError: AttValue: " or ' expected, line 325092, column 36

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:21810000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21810000.xml", line 206975
lxml.etree.XMLSyntaxError: error parsing attribute name, line 206975, column 28

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21820000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21820000.xml", line 193310
lxml.etree.XMLSyntaxError: expected '>', line 193310, column 29

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:21825000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21825000.xml", line 1760
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: DescriptorNamu line 1760 and DescriptorName, line 1760, column 102

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21835000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21835000.xml", line 91615
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: Inityals line 65535 and Initials, line 91615, column 48

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 84, in parse
    pmid= elem.find('MedlineCitation').find('PMID').text # First PMID is the right one
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 84, in parse
    pmid= elem.find('MedlineCitation').find('PMID').text # First PMID is the right one
AttributeError: 'NoneType' object has no attribute 'find'

XML File:21840000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21840000.xml", line 33762
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: CitationSubsut line 33762 and CitationSubset, line 33762, column 56

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

XML File:21845000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21845000.xml", line 41420
lxml.etree.XMLSyntaxError: error parsing attribute name, line 41420, column 41

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

XML File:21850000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21850000.xml", line 17478
lxml.etree.XMLSyntaxError: expected '>', line 17478, column 82

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 105, in parse
    years=getYears(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 78, in getYears
    years.append(child.find('Year').text)
AttributeError: 'NoneType' object has no attribute 'text'

XML File:21865000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21865000.xml", line 5990
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: ForeName line 5990 and ForeNamu, line 5990, column 50

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
  File "src/lxml/etree.pyx", line 2469, in lxml.etree._Attrib.__getitem__ (src/lxml/etree.c:72092)
KeyError: 'UI'

XML File:21870000 has a problem. Skipping...Error:Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 92, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 83, in parse
    for _,elem in context:
  File "src/lxml/iterparse.pxi", line 208, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155963)
  File "src/lxml/iterparse.pxi", line 193, in lxml.etree.iterparse.__next__ (src/lxml/etree.c:155671)
  File "src/lxml/iterparse.pxi", line 228, in lxml.etree.iterparse._read_more_events (src/lxml/etree.c:156298)
  File "src/lxml/parser.pxi", line 1362, in lxml.etree._FeedParser.feed (src/lxml/etree.c:116552)
  File "src/lxml/parser.pxi", line 589, in lxml.etree._ParserContext._handleParseResult (src/lxml/etree.c:107619)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/stephen/ExtraDrive1/MeSH_V3/21870000.xml", line 4199
lxml.etree.XMLSyntaxError: error parsing attribute name, line 4199, column 18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 95, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stephen/Documents/Projects/MeTeORv2/src/crawlPubMedFiles.py", line 107, in main
    indicies,pmids,meshids,miss=parse('{}/{}.xml'.format(storagedir,i),enumpmid,enumui,uis,meta,recover=True)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 95, in parse
    mesh = getTerms(elem)
  File "/home/stephen/Documents/Projects/MeTeORv2/src/utils.py", line 56, in getTerms
    mesh.append(m.find('DescriptorName').attrib['UI'])
AttributeError: 'NoneType' object has no attribute 'attrib'

